name: MacOS Virtual Machine

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: MacOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setting Up the MacOS Environment
        env:
          MAC_USER_PASSWORD: ${{ secrets.MAC_USER_PASSWORD }}
          VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
          MAC_REALNAME: ${{ secrets.MAC_REALNAME }}
        run: |
          source macos-run.sh "$MAC_USER_PASSWORD" "$VNC_PASSWORD" "$MAC_REALNAME"

      - name: Keep Running MacOS System
        run: |
          echo "MacOS system is running."
          echo "The Bore VNC endpoint should be shown above."
          sleep 6h
